String aboutacm =
    "ACM, the world's largest educational and scientific computing society, delivers resources that advance computing as a science and a profession. ACM provides the computing field's premier Digital Library and serves its members and the computing profession with leading-edge publications, conferences, and career resources.\nFounded in 1947, ACM has a rich history of contributing to the development of computer science and promoting its use for the benefit of society. The organization publishes numerous journals and conference proceedings, as well as a variety of educational resources for students and professionals alike.ACM also sponsors a number of special interest groups (SIGs) focused on specific areas of computing, such as artificial intelligence, computer graphics, and human-computer interaction. These SIGs provide a forum for members with similar interests to collaborate and share knowledge.";

String aboutacmevents =
    "Competitive programming contests: Like the ICPC, challenging students to solve problems collaboratively.Conferences and workshops: Bringing together experts to share knowledge, fostering research, and discussing industry trends.Educational webinars and courses: Providing professional development and skill-building opportunities for members.Career fairs and networking events: Connecting students and professionals with potential employers and collaborators.Local chapter activities: Engaging students and professionals through talks, workshops, and hackathons.";

String aboutBYTES =
    "Unleash your inner writer with Bytes, our ACM chapter's blogging platform! Share your unique perspectives, insightful reviews, and creative content. Bytes is your space to express yourself, engage with the community, and contribute to the vibrant world of ACM ABESEC. Join the conversation and leave your mark!";
String teampageTitle = "Every member of the society has always been passionate and hard working towards their goal, creating a positive work environment. Their support and will to help each other out in every way possible is what makes ACM-ABESEC a 'team'.";
